"""make wallet updated_at timezone-aware

Revision ID: 5d3d1971c1cb
Revises: ffcb21d7d47b
Create Date: 2026-07-05 01:11:00.379079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3d1971c1cb'
down_revision: Union[str, Sequence[str], None] = 'ffcb21d7d47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
